const productos = [
  { id: 1, nombre: 'Bolso casual floral', categoria: 'Bolsos', precio: 45, imagen: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=800&q=85', destacado: true },
  { id: 2, nombre: 'Morrallito premium', categoria: 'Morrales', precio: 42, imagen: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=85', destacado: true },
  { id: 3, nombre: 'Mochila urbana', categoria: 'Mochilas', precio: 52, imagen: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=85', destacado: true },
  { id: 4, nombre: 'Monedero Bobo clásico', categoria: 'Monederos', precio: 24, imagen: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=85' },
  { id: 5, nombre: 'Canguro multipocket', categoria: 'Canguros', precio: 31, imagen: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=85', destacado: true },
  { id: 6, nombre: 'Morrall modelo empanada', categoria: 'Morrales', precio: 30, imagen: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=85' },
  { id: 7, nombre: 'Cartera de hombro', categoria: 'Bolsos', precio: 48, imagen: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=85' },
  { id: 8, nombre: 'Monedero corazón', categoria: 'Monederos', precio: 22, imagen: 'https://images.unsplash.com/photo-1575032617751-6ddec2089882?auto=format&fit=crop&w=800&q=85' }
];
const categorias = [{ nombre: 'Bolsos', icono: '♢', imagen: productos[0].imagen }, { nombre: 'Morrales', icono: '◌', imagen: productos[1].imagen }, { nombre: 'Mochilas', icono: '▱', imagen: productos[2].imagen }, { nombre: 'Monederos', icono: '♡', imagen: productos[3].imagen }, { nombre: 'Canguros', icono: '⌁', imagen: productos[4].imagen }];
const masVendidos = [1, 2, 3, 5];
const grid = document.querySelector('#productGrid'); const bestGrid = document.querySelector('#bestGrid'); const categoryCards = document.querySelector('#categoryCards'); const filterButtons = document.querySelector('#filterButtons'); const emptyState = document.querySelector('#emptyState'); const searchInput = document.querySelector('#searchInput'); const toast = document.querySelector('#toast'); const menuToggle = document.querySelector('#menuToggle'); const mainNav = document.querySelector('#mainNav'); let categoriaActual = 'Todos';
function productCard(p) { return `<article class="product-card"><div class="product-image"><img src="${p.imagen}" alt="${p.nombre} Adri & Mishell" loading="lazy" />${p.destacado ? '<span class="badge">Más vendido</span>' : ''}</div><div class="product-info"><span class="product-category">${p.categoria}</span><h3 class="product-name">${p.nombre}</h3><div class="product-bottom"><span class="price">S/ ${p.precio.toFixed(2)}</span><button class="buy-button" data-id="${p.id}" type="button">Comprar ↗</button></div></div></article>`; }
function renderCategorias() { categoryCards.innerHTML = categorias.map((c) => `<button class="category-card" style="background-image:url('${c.imagen}')" data-category="${c.nombre}" type="button"><strong>${c.nombre}</strong><span>${c.icono}</span></button>`).join(''); filterButtons.innerHTML = `<button class="filter active" data-category="Todos">Todos</button>${categorias.map((c) => `<button class="filter" data-category="${c.nombre}">${c.nombre}</button>`).join('')}`; }
function seleccionarCategoria(categoria) { categoriaActual = categoria; document.querySelectorAll('.filter').forEach((button) => button.classList.toggle('active', button.dataset.category === categoria)); renderProducts(); document.querySelector('#catalogo').scrollIntoView({ behavior: 'smooth' }); }
function renderProducts() { const query = searchInput.value.trim().toLowerCase(); const filtrados = productos.filter((p) => (categoriaActual === 'Todos' || p.categoria === categoriaActual) && `${p.nombre} ${p.categoria}`.toLowerCase().includes(query)); emptyState.hidden = filtrados.length !== 0; grid.innerHTML = filtrados.map(productCard).join(''); }
function comprarProducto(id) { const p = productos.find((item) => item.id === id); const mensaje = `Hola Adri & Mishell 😊, quisiera comprar el producto: *${p.nombre}* (${p.categoria}), con precio S/ ${p.precio.toFixed(2)}. ¿Qué colores tienen disponibles?`; window.open(`https://wa.me/51988137193?text=${encodeURIComponent(mensaje)}`, '_blank', 'noopener'); toast.textContent = `Consulta por “${p.nombre}” preparada en WhatsApp`; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3500); }
renderCategorias(); bestGrid.innerHTML = masVendidos.map((id) => productCard(productos.find((p) => p.id === id))).join(''); document.addEventListener('click', (event) => { const categoryButton = event.target.closest('[data-category]'); if (categoryButton) seleccionarCategoria(categoryButton.dataset.category); const buyButton = event.target.closest('.buy-button'); if (buyButton) comprarProducto(Number(buyButton.dataset.id)); }); searchInput.addEventListener('input', renderProducts); renderProducts();

menuToggle.addEventListener('click', () => { const isOpen = mainNav.classList.toggle('is-open'); menuToggle.setAttribute('aria-expanded', String(isOpen)); menuToggle.setAttribute('aria-label', isOpen ? 'Cerrar menú' : 'Abrir menú'); });
mainNav.addEventListener('click', (event) => { if (event.target.closest('a')) { mainNav.classList.remove('is-open'); menuToggle.setAttribute('aria-expanded', 'false'); menuToggle.setAttribute('aria-label', 'Abrir menú'); } });
